### ISSUE TITLE
Java Crash on Fullscreen (F11): Explanation included.

### ISSUE THREAD

**Issue by Iomega0318** [hancin/Fullscreen-Windowed-Minecraft#12]
So I have the oddest crash happening, here is what happened and what is now occurring.

Minecraft was and has been running perfectly fine with this mod installed, my video drivers auto updated while I was away from my computer and coincidentally it caused minecraft to crash while this mod was active and in "Fullscreen". For some odd reason this also screwed up Waila (Hwyla) and was causing another crash, updating that mod seemed to fix that issue. Now here is where my current problem is, when I load minecraft it all seems fine but then and only when I hit F11 to go to Fullscreen it causes Java to crash  which doesn't spit out any information to the log file of course.. Going into options and using the Fullscreen option of course works fine but I assume that's because your mod requires the use of "F11" to activate? Anyways just thought I would pop on here for any suggestions you have of figuring out wth happened and maybe some ideas on fixing the issue?

My only guess is that when the drivers updated and your mod was active at the time of the crash that it caused some sort of error somewhere that is preventing me from "reactivating" your mod.. 

I will continue to trouble shoot on my end, but since you probably know more about your own mod and Java than I do I figured I would post here as well..

..Side note, I am also using version 1.4.1 now.

Thank you.

**Comment by hancin** [comment]
If you're using nvidia hardware this driver update may be the source of the issue. A lot of people are having issues, see [this reddit post](https://www.reddit.com/r/Minecraft/comments/5q05wu/psa_latest_nvidia_gpu_driver_crashes_minecraft/) as an example

**Comment by Iomega0318** [comment]
Gotcha! Also thank you, I will probably just rollback my drivers then until it can be fixed.
