### ISSUE TITLE
Crashing after Windows 10 Creator update.

### ISSUE THREAD

**Issue by Rader2146** [hancin/Fullscreen-Windowed-Minecraft#21]
v1.5.0
MC 1.11.2
Forge 2228

Minecraft worked great until Windows 10 decided to update.  Now I'm getting java crashes as soon as minecraft loads the main screen.  I removed mods 1 by 1 and this happens to be the culprit.

#blamemicrosoft

Minecraft Log
[2017-06-01-6.txt](https://github.com/hancin/Fullscreen-Windowed-Minecraft/files/1046661/2017-06-01-6.txt)

Java Error report
[hs_err_pid31788.txt](https://github.com/hancin/Fullscreen-Windowed-Minecraft/files/1046651/hs_err_pid31788.txt)

**Comment by Whalerus** [comment]
`Java` frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.java2d.d3d.D3DGraphicsDevice.getDeviceCapsNative(I)I+0
j  sun.java2d.d3d.D3DGraphicsDevice.access$000(I)I+1
j  sun.java2d.d3d.D3DGraphicsDevice$1.run()V+8
v  ~StubRoutines::call_stub
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub`
Update your java as this is a java bug or driver bug

**Comment by Rader2146** [comment]
Sorry,  I never came back to update this report.

This was directly tied to the windows 10 creators update and the problems it caused with java. Updating java didn't help and the java folks said (in different words) they didn't break it so they weren't trying to fix it.

My solution was to uninstall the abysmal creators update and I have had no problems since.  I have not followed up to see if any windows updates have sought to resolve the issue.
