### ISSUE TITLE
Mod not marked as supporting 1.12.2

### ISSUE THREAD

**Issue by C0rn3j** [hancin/Fullscreen-Windowed-Minecraft#24]
Hi, this mod is not marked as 1.12.2. I assume it works on that version since there's a 1.12.1 marked version.

https://minecraft.curseforge.com/projects/fullscreen-windowed-borderless-for-minecraft/files
please mark the 1.12.1 file as 1.12.2 too.

This "broke" my updater script.

**Comment by hancin** [comment]
I have updated the project on curse to include the new version support.

Let me know it that works for you.

**Comment by C0rn3j** [comment]
That works, but now I'm running into this issue.

https://github.com/hancin/Fullscreen-Windowed-Minecraft/issues/19
