### ISSUE TITLE
Borderless without resolution change, please?

### ISSUE THREAD

**Issue by AnrDaemon** [hancin/Fullscreen-Windowed-Minecraft#4]
I would really like borderless mode without resolution change.

**Comment by hancin** [comment]
Hi,

Can you give me more information on what you're looking for ? If borderless is enabled without any resolution change then the result would be a window you can't move or resize (unless you toggle "fullscreen" off again) the size it was when you pressed the key.

**Comment by AnrDaemon** [comment]
Yes, I'm looking for exactly that functionality.
I want to protect from accidental resizes (it screws the recorded material), and I have means to move even borderless windows where I want them, so that's not really an issue.
However, if you would remember the position and/or set the newly started client to the saved position, that would a bonus.

**Comment by hancin** [comment]
Version 1.3.0 for 1.8 and up now has that feature in the options!  

In the config file, change B:enableAdvancedFeatures and B:customFullscreenDimensions from false to true.

You'll then be able to change the X,Y, width and height so you can decide where it appears on the screen.

Example configuration (appear half size on right half of 2nd monitor):
 I:customFullscreenDimensionsH=1080
I:customFullscreenDimensionsW=960
I:customFullscreenDimensionsX=960
I:customFullscreenDimensionsY=0
(in general section) I:fullscreenMonitor=2
By default, X,Y refer to the primary monitor but changing the fullscreenMonitor option will allow you to position it on that monitor specifically.

Let me know if you have any questions or comments!

**Comment by AnrDaemon** [comment]
It works. Though, the startup sequence is least pleasant.
