### ISSUE TITLE
Exception Caught while changing mod configs in Single Player GUI -Config changes don't take effect.

### ISSUE THREAD

**Issue by JoelZBub** [hancin/Fullscreen-Windowed-Minecraft#8]
MC version : 1.8.9
Forge versions tested : 11.15.1.875 and 11.15.1.1902
FullscreenWindowed version : 1.10.2-1.3.0b

When attempting to change any mod config settings in-game while FullscreenWindowed is installed, no config changes take effect and an exception is caught during firing ConfigChangedEvent at com.hancinworld.fw.handler.ConfigurationHandler.onConfigurationChangedEvent.

Here is the forge log where it happens with FullscreenWindowed installed as the only mod:

[fml-client-latest.txt](https://github.com/hancin/Fullscreen-Windowed-Minecraft/files/400462/fml-client-latest.txt)

**Comment by hancin** [comment]
To close the loop on this issue, there was a patch included in version 1.4.1 and later working around this issue in 1.8.

There should no longer be a crash when saving / loading configs via the forge config GUI when the mod is installed.

Cheers.
